CREATE DATABASE todo DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_cl;

CREATE TABLE tasks (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    decription VARCHAR(64) NOT NULL,
    completed TINYINT(1) NOT NULL DEFAULT NOW(),
    last_updated DATABASE NOT NULL DEFAULT NOW() ON UPDATE NOW()
);